### ISSUE TITLE
Adding PS4 Support?

### ISSUE THREAD

**Issue by Cissamannen** [Synthlight/Nexomon-Extinction-Save-Editor#1]
Hello,

Is it possible to add PS4 support? It's named memory.dat as default when exported using Save Wizard.

I notice by removing the first 0x30 bytes of the file in HxD, it reads fine in the "windows" .dat format.
See added file. 

Removing the string:
`46 41 4C 4C 45 4E 00 00 18 00 00 00 02 00 00 00 01 00 00 00 00 00 00 02 B4 5D 3C F7 03 00 00 00 00 04 00 00 30 00 00 00 46 41 4C 4C 45 4E 00 01` - Basically block 00-2F
Makes the save readable in the editor just fine. I can see inventory, name, nexomons etc.

Note I only have 1 slot saved. If theres 2 saves, itll be 0x40 length, 3 0x50 length to remove.

I uploaded a save with 3 slots made in the beginning of the game aswell.
This information also from a user on SW Discord (Skiller):

B45D3CF7 = Always Slot 1 
565DCA65 =Always Slot 2 
D318F5A9 = Always Slot 3

+0x08 = Size 
+0x0C = Starting point
___

If only 1 Slot is used, you see B45xxxx value used (Top slot)

[memory.zip](https://github.com/Synthlight/Nexomon-Extinction-Save-Editor/files/5184760/memory.zip)

[3Slots.zip](https://github.com/Synthlight/Nexomon-Extinction-Save-Editor/files/5184909/3Slots.zip)

[PS4 EU.zip](https://github.com/Synthlight/Nexomon-Extinction-Save-Editor/files/5185058/PS4.EU.zip) - All save orders

**Comment by Synthlight** [comment]
I'll have to work out something for the header later, but from what I can tell, the header contains an array of the slots in the save, & what position they start at in the save.
This is doable, but more complicated. Will take some time.

**Comment by Synthlight** [comment]
To use your example bytes:
`46 41 4C 4C 45 4E 00 00 18 00 00 00 02 00 00 00 (slot count (int) ->) 01 00 00 00 00 00 00 02 B4 5D 3C F7 03 00 00 00 00 04 00 00 (offset first save starts at (int) ->) 30 00 00 00 46 41 4C 4C 45 4E 00 01`

Fora save with 3:
`46 41 4C 4C 45 4E 00 00 18 00 00 00 02 00 00 00 (slot count (int) ->) 03 00 00 00
00 00 00 02 56 5D CA 65 03 00 00 00 00 04 00 00 (offset first save starts at (int) ->) 50 00 00 00
D3 18 F5 A9 03 00 00 00 00 04 00 00 (offset second save starts at (int) ->) 58 04 00 00 B4 5D 3C F7
03 00 00 00 00 04 00 00 (offset third save starts at (int) ->) 60 08 00 00 46 41 4C 4C 45 4E 00 01
`

**Comment by Synthlight** [comment]
So I updated the [010 template](https://github.com/Synthlight/Nexomon-Extinction-Save-Editor/blob/master/Save-Template.bt) to work with this, the format looks like this:
![image](https://user-images.githubusercontent.com/1075166/92420902-e8428d80-f143-11ea-8232-3ee20074103e.png)

Feel free to use that in the mean time.

**Comment by Synthlight** [comment]
https://github.com/Synthlight/Nexomon-Extinction-Save-Editor/releases/tag/v1.3

Give it a shot and let me know how it works.
It seemed OK in my testing (and comparing the in/out files) so hopefully it works.

**Comment by Cissamannen** [comment]
Seems to run fine on my saves atleast. Everything showing up correct.. and yes they are early game saves, so im not sure how itll be with bigger saves, but as you say, it loads fine:)

**Comment by Synthlight** [comment]
Cool. Calling it fixed then. Reopen if needed.
