### ISSUE TITLE
Power Shard

### ISSUE THREAD

**Issue by novalkun** [Synthlight/Nexomon-Extinction-Save-Editor#2]
is there power shard on item list in save editor?

**Comment by Synthlight** [comment]
Did you even look?

**Comment by novalkun** [comment]
![2020-09-12](https://user-images.githubusercontent.com/43009254/92999575-2d9ffa00-f54c-11ea-96c8-c5652f6f5a04.png)

where should i look ?

**Comment by Synthlight** [comment]
![image](https://user-images.githubusercontent.com/1075166/92999984-3dd7bb00-f4f3-11ea-9bf6-3c63d7990887.png)
They aren't in alphabetical order. Yes, they are there.

**Comment by novalkun** [comment]
Wait. That is core. Not shard. I am looking for power shard

**Comment by Synthlight** [comment]
There is no such thing as a "power shard". The shards do not come in

**Comment by Synthlight** [comment]
![image](https://user-images.githubusercontent.com/1075166/93000601-76799380-f4f7-11ea-8c96-20c756e4091a.png)

There is leftover data for "shard-normal" (Power Shard) in some of the files, but it does not exist in the games item list.

**Comment by novalkun** [comment]
i see. thanks for the information. it seems the pedia have fooled me by listing 9 shards then -_-
