### ISSUE TITLE
Instructions on how to use the program please...

### ISSUE THREAD

**Issue by Petre2710** [Synthlight/Nexomon-Extinction-Save-Editor#3]
I really appreciate your work in trying to make a save editor, but I have a few "issues" in regards to how to use the program.
First off... What do I have to open after I download the zip project.
Please be more explicit in the readme file...

**Comment by Synthlight** [comment]
> What do I have to open after I download the zip project.
Instructions aren't going to help this. The "Code" button downloads the source code, NOT the release. I don't know why people keep expecting this to be different. I can't fix people downloading the wrong thing.

![image](https://user-images.githubusercontent.com/1075166/93031217-166a1680-f5f7-11ea-98de-46dc5bfd02d3.png)
![image](https://user-images.githubusercontent.com/1075166/93031287-8ed0d780-f5f7-11ea-887f-aa7706435b38.png)

After that, you just extract and run the exe. No. I will not add instructions telling people where to extract it or how to run the exe. They shouldn't need it.
