### ISSUE TITLE
no issue just wanted to say thanks

### ISSUE THREAD

**Issue by kurtamery929** [Synthlight/Nexomon-Extinction-Save-Editor#7]
hi i just wanted to message to say thank you so much for creating this editor. My little boy is playing is on the switch atm, I tried using cheats with atmosphere and it had been an absolute nightmare. never really expected to find an editor for the switch . It is so appreciated. Sorry for opening up an issue. never really delved into github other than downloading a few things for the switch and didnt know how else i could express my thanks
all the best

**Comment by Synthlight** [comment]
Your welcome. I haven't played in a while and I don't have a Switch, but the save format is *mostly* the same so I'm glad it still works.
